from Misc.Tier.aabKatze import Katze
from Misc.Tier.aabHund import Hund
from Misc.Tier.aabFisch import Fisch



katze1=Katze("Mitzi",19)
katze2=Katze("Elisabet",11)
katze3=Katze("Malo",5)
katze4=Katze("Tiger",7)
katze5=Katze("Gunter",2)
katze6=Katze("Hans Peter",9)
katze7=Katze("Garfield",22)
katze8=Katze("Neko",1)
katze9=Katze("Rekik",7)
katze10=Katze("Schmusi",2)
katze11=Katze("Pitsburg",3)
katze12=Katze("Lillo",5)
katze13=Katze("Ohnezahn",4)
katze14=Katze("Kitty",19)
katze15=Katze("Lilly",11)
katze16=Katze("Lucy",5)
katze17=Katze("Luna",7)
katze18=Katze("Zora",2)
katze19=Katze("Amy",9)
katze20=Katze("Bella",22)
katze21=Katze("Daisy",1)
katze22=Katze("Cleo",7)
katze23=Katze("Felix",2)
katze24=Katze("Findus",3)
katze25=Katze("Gizmo",5)
katze26=Katze("Urmel",4)

hund1=Hund("Prinz",6)
hund2=Hund("Luna",8)
hund3=Hund("Bella",2)
hund4=Hund("Emma",4)
hund5=Hund("Amy",4)
hund6=Hund("Kira",3)
hund7=Hund("Lilly",9)
hund8=Hund("Lucy",1)
hund9=Hund("Mia",1)
hund10=Hund("Sunny",2)
hund11=Hund("Nala",8)

fisch1=Fisch("Goldy",1)



katze1.mausfangen()
katze1.mausfangen()

katze1.lautgeben()
katze2.lautgeben()
katze3.lautgeben()
katze4.lautgeben()
katze5.lautgeben()
katze6.lautgeben()
katze7.lautgeben()
katze8.lautgeben()
katze9.lautgeben()
katze10.lautgeben()
katze11.lautgeben()
katze12.lautgeben()
katze13.lautgeben()
katze14.lautgeben()
katze15.lautgeben()
katze16.lautgeben()
katze17.lautgeben()
katze18.lautgeben()
katze19.lautgeben()
katze20.lautgeben()
katze21.lautgeben()
katze22.lautgeben()
katze23.lautgeben()
katze24.lautgeben()
katze25.lautgeben()
katze26.lautgeben()

hund1.lautgeben()
hund2.lautgeben()
hund3.lautgeben()
hund4.lautgeben()
hund5.lautgeben()
hund6.lautgeben()
hund7.lautgeben()
hund8.lautgeben()
hund9.lautgeben()
hund10.lautgeben()
hund11.lautgeben()

fisch1.lautgeben()